### PR TITLE
Replace MW-OAuth2Client-Gamma with OpenIDConnect

### PR DESCRIPTION
**Pull request by GAsplund**
This allows configuration towards more generic OpenID Connect issuers, including Gamma. It's still not entirely generic however, as some claims (such as cid for username) will need to be hard coded.

# UX Improvements
- New themes: Cititzen, Vector 2022 and Minerva Neue
- Use Vector 2022 as default skin for mobile compatibility
- New extensions: PdfHandler, Math and MultimediaViewer

# Code Improvements
- Documentation in README.md
- Remove old Gamma docker-compose (use the centrally hosted Gamma for development)

# Known Issues
- There is no way to log in directly through Gamma without navigating to the login form or disabling local login
  - Login via Gamma is done through PluggableAuth that sends a POST request directly from the browser to the login endpoint to get redirected

### CODE REVIEW

**Review by simon-wg — COMMENTED** [review]
I'm not too familiar with php, but from what I can see and read in the mediawiki documentation it looks good.

However, in the README there is a mention of updating from earlier than version 1.39, but we still use version 1.35 in the dockerfile.

Additionally we've removed the old GAMMA_AUTHORIZED_GROUPS environment variable it seems. Do we have some other way of limiting access to certain wikis?

All in all it looks great though!

**Comment by GAsplund** [comment]
> I'm not too familiar with php, but from what I can see and read in the mediawiki documentation it looks good.
> 
> However, in the README there is a mention of updating from earlier than version 1.39, but we still use version 1.35 in the dockerfile.
> 
> Additionally we've removed the old GAMMA_AUTHORIZED_GROUPS environment variable it seems. Do we have some other way of limiting access to certain wikis?
> 
> All in all it looks great though!

Oops, don't know how I missed upgrading to 1.39. I will go ahead and fix that.

GAMMA_AUTHORIZED_GROUPS was removed in part due to the new framework not supporting it but also that Gamma 2.0 allows you to put restrictions on which groups may authenticate with that client.

**Comment by simon-wg** [comment]
Allright! Ah yeah I forgot about that detail in Gamma 2.0 😋. 

Thanks for the explanation, in that case I'll approve as soon as the mediawiki is updated.

I have however read some reports of mediawiki 1.39 breaking if you use the Vector 2022 extension due to it being bundled with 1.39 so just beware of that.

**Comment by simon-wg** [comment]
Actually, scratch that, it appears to only affect instances where the Vector 2022 extension was installed before the update.

**Review by simon-wg — APPROVED** [review]
Lgtm 😎

**Pull request merged**
